name: "Run CI 1"

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.10.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run test
