name: "Run CI 1"

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -fsSL https://pixi.sh/install.sh | bash
      - run: pixi install 
      - run: pixi run test

